export const SET_START_WEIGHT = "SET_START_WEIGHT";
export const SET_GOAL_WEIGHT = "SET_GOAL_WEIGHT";
export const SET_WEEKLY_CHANGE = "SET_WEEKLY_CHANGE";
export const SET_DAILY_KCAL_CHANGE = "SET_DAILY_KCAL_CHANGE";
export const SET_START_DATE = "SET_START_DATE";
export const SET_WEEKS_FOR_AVG = "SET_WEEKS_FOR_AVG";
export const TOGGLE_MEASUREMENT_SYSTEM = "TOGGLE_MEASUREMENT_SYSTEM"

export const SET_KCAL_AND_KG = "SET_KCAL_AND_KG";
export const SET_WEEKLY_KCAL_AND_KG = "SET_WEEKLY_KCAL_AND_KG";
export const SET_WEEKLY_TDEE = "SET_WEEKLY_TDEE";

export const ADD_ANOTHER_WEEK = "ADD_ANOTHER_WEEK";
export const LOCK_WEEK = "LOCK_WEEK";


