export const SET_START_WEIGHT = "SET_START_WEIGHT";
export const SET_GOAL_WEIGHT = "SET_GOAL_WEIGHT";
export const SET_WEEKLY_CHANGE = "SET_WEEKLY_CHANGE";
export const SET_DAILY_KCAL_CHANGE = "SET_DAILY_KCAL_CHANGE";
export const SET_START_DATE = "SET_START_DATE";
export const SET_GAINING = "SET_GAINING";

export const SET_KCAL_AND_KG = "SET_KCAL_AND_KG";
export const SET_WEEKLY_KCAL_AND_KG = "SET_WEEKLY_KCAL_AND_KG";

export const ADD_ANOTHER_WEEK = "ADD_ANOTHER_WEEK";

// export const SET_RESULTS = "SET_RESULTS";

// export const FETCH_STARTED = "FETCH_STARTED";
// export const FETCH_FINISHED = "FETCH_FINISHED";

// export const CLOSE_MODAL = "CLOSE_MODAL";
// export const OPEN_MODAL = "OPEN_MODAL";

// export const SET_ERROR = "SET_ERROR";

// export const SET_LOADED_IMAGES = "SET_LOADED_IMAGES";
// export const CLEAR_LOADED_IMAGES = "CLEAR_LOADED_IMAGES";
